class CountryList
=begin

http://www.worldatlas.com/aatlas/ctycodes.htm

//jQueryfy
j = $
var f1 = j('font:eq(4)') // 2 cod
var f2 = j('font:eq(6)') // 3 cod
var f3 = j('font:eq(8)') // id
var f4 = j('font:eq(10)') // name

function split_lines(j_node){  return j_node.html().replace('<br>','').replace(/\n/g, '').split('<br>') }

f1 = split_lines(f1)
f2 = split_lines(f2)
f3 = split_lines(f3)
f4 = split_lines(f4)

var out = []
j(f1).each(function(i,e){
 out.push([f3[i], "'"+f4[i]+"'", "'"+f2[i]+"'", "'"+f1[i]+"'" ].join(','))
})

"["+out.join('],[')+ "]"
=end

  @@list = [  [4,'AFGHANISTAN','AFG','AF'],
              [8,'ALBANIA','ALB','AL'],
              [12,'ALGERIA','DZA','DZ'],
              [16,'AMERICAN SAMOA','ASM','AS'],
              [20,'ANDORRA','AND','AD'],
              [24,'ANGOLA','AGO','AO'],
              [60,'ANGUILLA','AIA','AI'],
              [10,'ANTARCTICA','ATA','AQ'],
              [28,'ANTIGUA AND BARBUDA','ATG','AG'],
              [32,'ARGENTINA','ARG','AR'],
              [51,'ARMENIA','ARM','AM'],
              [533,'ARUBA','ABW','AW'],
              [36,'AUSTRALIA','AUS','AU'],
              [40,'AUSTRIA','AUT','AT'],
              [31,'AZERBAIJAN','AZE','AZ'],
              [44,'BAHAMAS','BHS','BS'],
              [48,'BAHRAIN','BHR','BH'],
              [50,'BANGLADESH','BGD','BD'],
              [52,'BARBADOS','BRB','BB'],
              [112,'BELARUS','BLR','BY'],
              [056,'BELGIUM','BEL','BE'],
              [84,'BELIZE','BLZ','BZ'],
              [204,'BENIN','BEN','BJ'],
              [60,'BERMUDA','BMU','BM'],
              [64,'BHUTAN','BTN','BT'],
              [68,'BOLIVIA','BOL','BO'],
              [70,'BOSNIA AND HERZEGOWINA','BIH','BA'],
              [72,'BOTSWANA','BWA','BW'],
              [74,'BOUVET ISLAND','BVT','BV'],
              [76,'BRAZIL','BRA','BR'],
              [86,'BRITISH INDIAN OCEAN TERRITORY','IOT','IO'],
              [96,'BRUNEI DARUSSALAM','BRN','BN'],
              [100,'BULGARIA','BGR','BG'],
              [854,'BURKINA FASO','BFA','BF'],
              [108,'BURUNDI','BDI','BI'],
              [116,'CAMBODIA','KHM','KH'],
              [120,'CAMEROON','CMR','CM'],
              [124,'CANADA','CAN','CA'],
              [132,'CAPE VERDE','CPV','CV'],
              [136,'CAYMAN ISLANDS','CYM','KY'],
              [140,'CENTRAL AFRICAN REPUBLIC','CAF','CF'],
              [148,'CHAD','TCD','TD'],
              [152,'CHILE','CHL','CL'],
              [156,'CHINA','CHN','CN'],
              [162,'CHRISTMAS ISLAND','CXR','CX'],
              [166,'COCOS (KEELING) ISLANDS','CCK','CC'],
              [170,'COLOMBIA','COL','CO'],
              [174,'COMOROS','COM','KM'],
              [178,'CONGO','COG','CG'],
              [180,'CONGO, THE DRC','COD','CD'],
              [184,'COOK ISLANDS','COK','CK'],
              [188,'COSTA RICA','CRI','CR'],
              [384,'COTE D`IVOIRE','CIV','CI'],
              [191,'CROATIA (local name: Hrvatska)','HRV','HR'],
              [192,'CUBA','CUB','CU'],
              [196,'CYPRUS','CYP','CY'],
              [203,'CZECH REPUBLIC','CZE','CZ'],
              [208,'DENMARK','DNK','DK'],
              [262,'DJIBOUTI','DJI','DJ'],
              [212,'DOMINICA','DMA','DM'],
              [214,'DOMINICAN REPUBLIC','DOM','DO'],
              [626,'EAST TIMOR','TMP','TP'],
              [218,'ECUADOR','ECU','EC'],
              [818,'EGYPT','EGY','EG'],
              [222,'EL SALVADOR','SLV','SV'],
              [226,'EQUATORIAL GUINEA','GNQ','GQ'],
              [232,'ERITREA','ERI','ER'],
              [233,'ESTONIA','EST','EE'],
              [231,'ETHIOPIA','ETH','ET'],
              [238,'FALKLAND ISLANDS (MALVINAS)','FLK','FK'],
              [234,'FAROE ISLANDS','FRO','FO'],
              [242,'FIJI','FJI','FJ'],
              [246,'FINLAND','FIN','FI'],
              [250,'FRANCE','FRA','FR'],
              [249,'FRANCE, METROPOLITAN','FXX','FX'],
              [254,'FRENCH GUIANA','GUF','GF'],
              [258,'FRENCH POLYNESIA','PYF','PF'],
              [260,'FRENCH SOUTHERN TERRITORIES','ATF','TF'],
              [266,'GABON','GAB','GA'],
              [270,'GAMBIA','GMB','GM'],
              [268,'GEORGIA','GEO','GE'],
              [276,'GERMANY','DEU','DE'],
              [288,'GHANA','GHA','GH'],
              [292,'GIBRALTAR','GIB','GI'],
              [300,'GREECE','GRC','GR'],
              [304,'GREENLAND','GRL','GL'],
              [308,'GRENADA','GRD','GD'],
              [312,'GUADELOUPE','GLP','GP'],
              [316,'GUAM','GUM','GU'],
              [320,'GUATEMALA','GTM','GT'],
              [324,'GUINEA','GIN','GN'],
              [624,'GUINEA-BISSAU','GNB','GW'],
              [328,'GUYANA','GUY','GY'],
              [332,'HAITI','HTI','HT'],
              [334,'HEARD AND MC DONALD ISLANDS','HMD','HM'],
              [336,'HOLY SEE (VATICAN CITY STATE)','VAT','VA'],
              [340,'HONDURAS','HND','HN'],
              [344,'HONG KONG','HKG','HK'],
              [348,'HUNGARY','HUN','HU'],
              [352,'ICELAND','ISL','IS'],
              [356,'INDIA','IND','IN'],
              [360,'INDONESIA','IDN','ID'],
              [364,'IRAN (ISLAMIC REPUBLIC OF)','IRN','IR'],
              [368,'IRAQ','IRQ','IQ'],
              [372,'IRELAND','IRL','IE'],
              [376,'ISRAEL','ISR','IL'],
              [380,'ITALY','ITA','IT'],
              [388,'JAMAICA','JAM','JM'],
              [392,'JAPAN','JPN','JP'],
              [400,'JORDAN','JOR','JO'],
              [398,'KAZAKHSTAN','KAZ','KZ'],
              [404,'KENYA','KEN','KE'],
              [296,'KIRIBATI','KIR','KI'],
              [408,'KOREA, D.P.R.O.','PRK','KP'],
              [410,'KOREA, REPUBLIC OF','KOR','KR'],
              [414,'KUWAIT','KWT','KW'],
              [417,'KYRGYZSTAN','KGZ','KG'],
              [418,'LAOS ','LAO','LA'],
              [428,'LATVIA','LVA','LV'],
              [422,'LEBANON','LBN','LB'],
              [426,'LESOTHO','LSO','LS'],
              [430,'LIBERIA','LBR','LR'],
              [434,'LIBYAN ARAB JAMAHIRIYA','LBY','LY'],
              [438,'LIECHTENSTEIN','LIE','LI'],
              [440,'LITHUANIA','LTU','LT'],
              [442,'LUXEMBOURG','LUX','LU'],
              [446,'MACAU','MAC','MO'],
              [807,'MACEDONIA','MKD','MK'],
              [450,'MADAGASCAR','MDG','MG'],
              [454,'MALAWI','MWI','MW'],
              [458,'MALAYSIA','MYS','MY'],
              [462,'MALDIVES','MDV','MV'],
              [466,'MALI','MLI','ML'],
              [470,'MALTA','MLT','MT'],
              [584,'MARSHALL ISLANDS','MHL','MH'],
              [474,'MARTINIQUE','MTQ','MQ'],
              [478,'MAURITANIA','MRT','MR'],
              [480,'MAURITIUS','MUS','MU'],
              [175,'MAYOTTE','MYT','YT'],
              [484,'MEXICO','MEX','MX'],
              [583,'MICRONESIA, FEDERATED STATES OF','FSM','FM'],
              [498,'MOLDOVA, REPUBLIC OF','MDA','MD'],
              [492,'MONACO','MCO','MC'],
              [496,'MONGOLIA','MNG','MN'],
              [500,'MONTSERRAT','MSR','MS'],
              [504,'MOROCCO','MAR','MA'],
              [508,'MOZAMBIQUE','MOZ','MZ'],
              [104,'MYANMAR (Burma) ','MMR','MM'],
              [516,'NAMIBIA','NAM','NA'],
              [520,'NAURU','NRU','NR'],
              [524,'NEPAL','NPL','NP'],
              [528,'NETHERLANDS','NLD','NL'],
              [530,'NETHERLANDS ANTILLES','ANT','AN'],
              [540,'NEW CALEDONIA','NCL','NC'],
              [554,'NEW ZEALAND','NZL','NZ'],
              [558,'NICARAGUA','NIC','NI'],
              [562,'NIGER','NER','NE'],
              [566,'NIGERIA','NGA','NG'],
              [570,'NIUE','NIU','NU'],
              [574,'NORFOLK ISLAND','NFK','NF'],
              [580,'NORTHERN MARIANA ISLANDS','MNP','MP'],
              [578,'NORWAY','NOR','NO'],
              [512,'OMAN','OMN','OM'],
              [586,'PAKISTAN','PAK','PK'],
              [585,'PALAU','PLW','PW'],
              [591,'PANAMA','PAN','PA'],
              [598,'PAPUA NEW GUINEA','PNG','PG'],
              [600,'PARAGUAY','PRY','PY'],
              [604,'PERU','PER','PE'],
              [608,'PHILIPPINES','PHL','PH'],
              [612,'PITCAIRN','PCN','PN'],
              [616,'POLAND','POL','PL'],
              [620,'PORTUGAL','PRT','PT'],
              [630,'PUERTO RICO','PRI','PR'],
              [634,'QATAR','QAT','QA'],
              [638,'REUNION','REU','RE'],
              [642,'ROMANIA','ROM','RO'],
              [643,'RUSSIAN FEDERATION','RUS','RU'],
              [646,'RWANDA','RWA','RW'],
              [659,'SAINT KITTS AND NEVIS','KNA','KN'],
              [662,'SAINT LUCIA','LCA','LC'],
              [670,'SAINT VINCENT AND THE GRENADINES','VCT','VC'],
              [882,'SAMOA','WSM','WS'],
              [674,'SAN MARINO','SMR','SM'],
              [678,'SAO TOME AND PRINCIPE','STP','ST'],
              [682,'SAUDI ARABIA','SAU','SA'],
              [686,'SENEGAL','SEN','SN'],
              [690,'SEYCHELLES','SYC','SC'],
              [694,'SIERRA LEONE','SLE','SL'],
              [702,'SINGAPORE','SGP','SG'],
              [703,'SLOVAKIA (Slovak Republic)','SVK','SK'],
              [705,'SLOVENIA','SVN','SI'],
              [90,'SOLOMON ISLANDS','SLB','SB'],
              [706,'SOMALIA','SOM','SO'],
              [710,'SOUTH AFRICA','ZAF','ZA'],
              [239,'SOUTH GEORGIA AND SOUTH S.S.','SGS','GS'],
              [724,'SPAIN','ESP','ES'],
              [144,'SRI LANKA','LKA','LK'],
              [654,'ST. HELENA','SHN','SH'],
              [666,'ST. PIERRE AND MIQUELON','SPM','PM'],
              [736,'SUDAN','SDN','SD'],
              [740,'SURINAME','SUR','SR'],
              [744,'SVALBARD AND JAN MAYEN ISLANDS','SJM','SJ'],
              [748,'SWAZILAND','SWZ','SZ'],
              [752,'SWEDEN','SWE','SE'],
              [756,'SWITZERLAND','CHE','CH'],
              [760,'SYRIAN ARAB REPUBLIC','SYR','SY'],
              [158,'TAIWAN, PROVINCE OF CHINA','TWN','TW'],
              [762,'TAJIKISTAN','TJK','TJ'],
              [834,'TANZANIA, UNITED REPUBLIC OF','TZA','TZ'],
              [764,'THAILAND','THA','TH'],
              [768,'TOGO','TGO','TG'],
              [772,'TOKELAU','TKL','TK'],
              [776,'TONGA','TON','TO'],
              [780,'TRINIDAD AND TOBAGO','TTO','TT'],
              [788,'TUNISIA','TUN','TN'],
              [792,'TURKEY','TUR','TR'],
              [795,'TURKMENISTAN','TKM','TM'],
              [796,'TURKS AND CAICOS ISLANDS','TCA','TC'],
              [798,'TUVALU','TUV','TV'],
              [800,'UGANDA','UGA','UG'],
              [804,'UKRAINE','UKR','UA'],
              [784,'UNITED ARAB EMIRATES','ARE','AE'],
              [826,'UNITED KINGDOM','GBR','GB'],
              [840,'UNITED STATES','USA','US'],
              [581,'U.S. MINOR ISLANDS','UMI','UM'],
              [858,'URUGUAY','URY','UY'],
              [860,'UZBEKISTAN','UZB','UZ'],
              [548,'VANUATU','VUT','VU'],
              [862,'VENEZUELA','VEN','VE'],
              [704,'VIET NAM','VNM','VN'],
              [92,'VIRGIN ISLANDS (BRITISH)','VGB','VG'],
              [850,'VIRGIN ISLANDS (U.S.)','VIR','VI'],
              [876,'WALLIS AND FUTUNA ISLANDS','WLF','WF'],
              [732,'WESTERN SAHARA','ESH','EH'],
              [887,'YEMEN','YEM','YE'],
              [891,'Yugoslavia (Serbia and Montenegro)','YUG','YU'],
              [894,'ZAMBIA','ZMB','ZM'],
              [716,'ZIMBABWE','ZWE','ZW']]
  def self.read()
    return @@list
  end
  
  def self.include_param?(num)
    num = num.to_i
    raise('Country param is not a Integer') unless num.is_a? Integer
    
    @@list.each do |l|
      return true if l[0] == num
    end
    
    return false
  end
end